server:
  port: 8088

spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:mongopassword@localhost:27017/search?authSource=admin}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
